# Pull base image.
FROM ubuntu

RUN apt-get update && apt-get -y install vim python-pip
RUN pip install glances
RUN pip install statsd

ADD assets/glances.conf /etc/glances.conf

CMD exec glances -t 10 -C "/etc/glances.conf" --export-statsd --quiet

